### PR TITLE
Update SNES boxart from Accurate USA Cover Art collection

### PR DESCRIPTION
**Pull request by RobLoach**
This set is from Jolu42.

References libretro-thumbnails/libretro-thumbnails#80

### CODE REVIEW

**Comment by RobLoach** [comment]
@kwyxz Looks like some are better, some are not...

**Comment by kwyxz** [comment]
So... should we merge? I was planning on doing a case-by-case examination, which will take time, but it'd be a bummer to replace some of our high quality boxarts with some lesser ones :)

**Comment by RobLoach** [comment]
The other thing we could do is just add the ones that we're missing.

**Comment by kwyxz** [comment]
Absolutely, that would be a great start. Though I don't think we are missing much especially the US ones as they're the easiest to find.

**Comment by kwyxz** [comment]
I started a having a look. Their naming is not consistent with the No-Intro (which is ours). It's going to take a little while!

**Comment by kwyxz** [comment]
FWIW I updated the NES repo with the "Accurate" versions after carefully reviewing them one by one : https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/commit/8433c2403ef638f3d5abc6aa6f061ba635b85466

The longest part of the work was to rename them to follow the No-Intro names. Turns out some versions were so very similar they probably were identical or from the same source. But most of theirs were better than ours.

**Comment by Khronikos** [comment]
> 
> 
> FWIW I updated the NES repo with the "Accurate" versions after carefully reviewing them one by one : [libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System@8433c24](https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/commit/8433c2403ef638f3d5abc6aa6f061ba635b85466)
> 
> The longest part of the work was to rename them to follow the No-Intro names. Turns out some versions were so very similar they probably were identical or from the same source. But most of theirs were better than ours.

Hey just a heads up man. I love what you guys have done in helping get all this stuff on here. I have been in contact with the creator of a lot of these thumbnails. I really love his work. I am currently planning on a lot of polishing and replacing in the databases for thumbnails.

I have gone over our current, as of today, database on NES and redid basically everything. Jolu's work needs desaturation or gamma changes among other small tweaks, and at times there is nothing I can do to match properly. Usually I found it is saturation that is too much with his work. Other than that it is impeccable.

His work looks A LOT more accurate now. And since 90% of his stuff is better than whatever we have in the database, it's going to go in then. I have carefully vetted the color and accuracy of boxes on ebay all from legit sources, and pretty much we will be changing a good chunk of what is currently there when I get the color down perfectly.

Problems with our current database: tons of cropping errors, tons of box errors, color issues, fade issues, real scans being slanted, low resolution, et cetera. All of this stuff will be mostly fixed for a large majority of the images. I am REALLY happy how my adjusted Zelda, Ninja Gaiden, Mega Man, Mario, and Dragon Warrior arts turned out. It's a massive improvement.

I am using lanczos3 through Faststone to convert images to 512 using width only resizing and no compression. It would be awesome if you could do this for whatever stuff you are putting into the database so I don't have to redo these things. You can easily open their batch convertor and then click on the adjustments tab in advanced. It will give you control over saturation and gamma among various other things. The only thing it does not give control over is complete gamma and brightness access to RGB separately, which means I can't really fix some of the major issues with say blue in some box arts. 

Obviously, this is for when you convert HIS work or I guess any other work with larger proportions. If this is too much trouble no problem. I really love working on this stuff, but we don't really have definitive characteristics for the thumbnails, and I am trying my best to change so people don't have to keep submitting stuff.

I did the 32X work a while ago, but I might actually redo it with a slightly more accurate color presentation. It just depends on how I feel with the original box art and the differences between what we have now and what he has there.

As I said in 90% of cases his box art is better, way better, but it was not accepted or chosen because of the issues I have stated.

It does take a lot of work though. I will rename everything for the Revs along with the non Revs for US, but I won't do any more than that. And there are definitely a few superior, but lower quality, thumbs that I won't be moving because it was too hard to get his to look like it should. I rated about 50 or so of them in our database as probably better, but that will be lesser as I go through the new converting process.

A ton of stuff is massively improved over what we have now though. Thanks for you help. Have a nice day.

**Comment by RobLoach** [comment]
That sounds exciting! Thanks for pushing this forwards :+1:

**Comment by Khronikos** [comment]
> 
> 
> That sounds exciting! Thanks for pushing this forwards +1

Thank you for the kind words. Yes, most of the awful work is done. Now I will look to customize the major franchise work to be as accurate as possible. Most of them will not get this attention as I don't have the time, but everything else is looking lovely. After that I just rename, delete, and then dump them on you.

At some point in the next 4 months I will be doing SNES and Genesis, though, I think some others are working on those too. I think NES is probably the worst of it at least I hope so.

Have a good day man.

**Comment by kwyxz** [comment]
@Khronikos it seems like you have a great meticulous approach to Jolu42's thumbs so I have absolutely no objection with leaving them up to you! Right now I am focusing on the covers that we are _missing_ in the NES collection, and the majority of them are either Japanese or obscure asian bootlegs so they're not covered by his sets. Feel free to tackle SNES and Genesis as well, I will focus on the covers he doesn't provide (last time I checked he was only doing US covers). Thanks!

**Comment by Khronikos** [comment]
Hi, thanks for the post. What everyone is doing is definitely a great foundation. Since most will be batch converted, and I won’t be doing all of them by hand or anything crazy, people are free to improve the color balance and I expect some people might want to do it for some games. I will probably not do too much customized work for colors atm as I just want to get them in. I’ll do a few of the bad cases. But it is definitely a massive improvement from what I can see. I’ll be sending a link to Jolu, I really wish he was as crazy about color accuracy as he was about his box details! Not to give him more work, but just to get a sense of how accurate and lovely they can be. Oh well. That’s what people are here for I guess.

My hope is to get all the stuff that has multiple posts and any inferior stuff out of the database, and then if people want they can just edit these with software if they want to make a really accurate version. From what I see on Ebay, and my own childhood, I will have to make a few compromises, but it’s going well so far. Just have to get things renamed here and deleted in the database. It appears there is NO WAY to delete multiple entries in the database? Well that will take me some time to delete and rename lol.

Some of Jolu’s stuff would obviously need an RGB editor with more controls though. I can’t get a few things to be accurate for sure, but a lot of them are close. I’m not quite sure why he does things so saturated, but his work really is fantastic on the box details. Finally our SM3 will have the proper buttons lol. Have a good day. I love all the niche stuff you guys dig up. Some of the Japanese covers I really love.

P.S. He has some random things about Japanese covers, but I haven’t checked it much, but if you wanted to check in on his stuff you can google his name and reddit and it should come up. Thanks for the heads up on your work. Much appreciated.

**Comment by Khronikos** [comment]
> 
> 
> @Khronikos it seems like you have a great meticulous approach to Jolu42's thumbs so I have absolutely no objection with leaving them up to you! Right now I am focusing on the covers that we are _missing_ in the NES collection, and the majority of them are either Japanese or obscure asian bootlegs so they're not covered by his sets. Feel free to tackle SNES and Genesis as well, I will focus on the covers he doesn't provide (last time I checked he was only doing US covers). Thanks!

Yeah looks like I will be doing SNES first. He's still working on NES, and it was causing some issues. He is making improvements, and I gave him an email about the poor grid patterns on boxes like Mega Man. Since he is done with SNES, I guess I will start with this. I was hoping this could be approved first though. Is there something holding this pull request up? I just want the newest database I can have before I do any color balance, as with NES it just becomes a waste of time if people are still working on a lot of changes.

**Review by kwyxz — APPROVED** [review]
Looks good to me.

**Comment by Khronikos** [comment]
Just a quick update on this. Jolu is still redoing or finishing his art for SNES and NES. So I just stopped things until he is done, at which point I will still go through the database and redo things with Lanczos and get them properly finished as well clean the database of any garbage we don't need. But it will be a bit I guess. I don't want to do anything now as I don't want to redo anything after submission.

**Pull request merged**
