### PR TITLE
Batman and Robin Adventures (USA)

### PR DESCRIPTION
**Pull request by andrexxito**
BatmanandRobinAdventuresof(US)

### CODE REVIEW

**Comment by andrexxito** [comment]
Batman and Robin Adventures (USA)

**Comment by RobLoach** [comment]
The images look great! Just need to be uploaded in as files in the PR :wink: 

Thanks a lot!

**Review by RobLoach — CHANGES_REQUESTED** [review]
Missing images.

**Comment by RobLoach** [comment]
Should be Adventure of Batman & Robin, The

**Pull request closed without merging**
