### PR TITLE
NSO

### PR DESCRIPTION
**Pull request by gerad-not-edgar**

### CODE REVIEW

**Comment by gerad-not-edgar** [comment]
@MarcoEstevez any chance I could get a merge for this? Thanks

**Comment by RobLoach** [comment]
Is it just me or do the images look super desaturated? The blacks are more grey than black....

Screenshot from 2024-07-08 12-18-57

**Comment by gerad-not-edgar** [comment]
I see it as well, but I also think the current one is oversaturated/black crush. If this is good enough for the big N itself, it's good enough for me. The quality is definitely better in the new one. Look at the lettering

**Comment by gerad-not-edgar** [comment]
@RobLoach I contrasted up Killer Instinct. Does this work for you?
image

**Comment by RobLoach** [comment]
Thanks!

**Pull request merged**
